name: olympus_fleet_git_sovereign
description: Project GitSovereign - The Firehorse Interaction Surface.
version: 0.1.0

environment:
  sdk: ">=3.11.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Sovereign Federated Interface dependencies
  provider: ^6.1.2
  web: ^1.1.0 # Required for WasmGC/dart:js_interop
  vector_math: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
